[package]
name = "revenq"
description = "A concurrent, revision-based event queue implementation"
version = "0.4.1"
authors = ["Alain Zscheile <fogti+devel@ytrizja.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/reclutch-nursery/revenq"
readme = "README.md"
exclude = ["/.github/", "Cargo.toml"]

[features]
default = []

[dependencies]
event-listener = ">= 2.2, < 2.6"
once_cell = ">= 1.4, < 1.6"

[dependencies.stable_deref_trait]
version = "1"
default-features = false

[dev-dependencies]
async-channel = "1.5"
async-executor = "1.4"
criterion = "0.3"
futures-lite = "1.11"
num_cpus = "1.13"

[[bench]]
name = "queue"
harness = false

[[example]]
name = "queue"
